const KEY="mctraining_progress_v2";
const $=id=>document.getElementById(id);
const modules=[
{id:"grill",emoji:"🍔",title:"Grill Station",cat:"Kitchen",xp:80,desc:"Learn setup, station habits, and teamwork.",lesson:["Check the station before you start.","Keep your area tidy.","Ask a trainer if a step is unclear."],checks:["Station checked","Tools ready","Trainer feedback"],tips:["Clean as you go.","Ask before guessing."],q:"What should you do if unsure?",opts:["Guess","Ask a trainer","Skip it"],a:1},
{id:"fries",emoji:"🍟",title:"Fries Station",cat:"Kitchen",xp:70,desc:"Practise timing, portions, and stock checks.",lesson:["Keep the area ready.","Watch timers.","Tell the team when stock is low."],checks:["Timers understood","Portions practised","Stock checked"],tips:["Freshness matters.","Communicate early."],q:"What helps the station run better?",opts:["Using timers","No communication","Messy station"],a:0},
{id:"counter",emoji:"🧾",title:"Front Counter",cat:"Service",xp:90,desc:"Improve greetings, orders, and customer confidence.",lesson:["Greet clearly.","Listen carefully.","Ask for help with hard questions."],checks:["Greeting practised","Order flow practised","Help process known"],tips:["Clear beats fast.","Stay polite."],q:"What helps with a hard question?",opts:["Ask for help","Panic","Leave it"],a:0},
{id:"clean",emoji:"🧽",title:"Cleanliness",cat:"Cleanliness",xp:60,desc:"Keep areas clean, safe, and ready.",lesson:["Check tables and floors.","Deal with mess quickly.","Tell someone if help is needed."],checks:["Tables checked","Floors checked","Supplies checked"],tips:["Small checks stop big mess.","Safety first."],q:"Why clean small messes quickly?",opts:["To stop bigger problems","No reason","To slow down"],a:0}
];
let state=loadState();
let selected=getUrlModule()||state.last||modules[0].id;
let filter="All";
let tab="lesson";
function getUrlModule(){try{let id=new URLSearchParams(location.search).get("module");return modules.some(m=>m.id===id)?id:null}catch{return null}}
function loadState(){try{return Object.assign({xp:0,done:{},checks:{},last:null},JSON.parse(localStorage.getItem(KEY)||"{}"))}catch{return{xp:0,done:{},checks:{},last:null}}}
function saveState(){localStorage.setItem(KEY,JSON.stringify(state))}
function getModule(id){return modules.find(m=>m.id===id)||modules[0]}
function getChecks(id){let m=getModule(id);if(!state.checks[id])state.checks[id]=Array(m.checks.length).fill(false);return state.checks[id]}
function getPercent(id){let count=getChecks(id).filter(Boolean).length+(state.done[id]?1:0);return Math.round(count/(getModule(id).checks.length+1)*100)}
function toast(text){let e=$("trainingToast");if(!e)return;e.textContent=text;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2000)}
function renderStats(){let done=Object.keys(state.done).length;$("statLevel").textContent=Math.floor(state.xp/150)+1;$("statXp").textContent=state.xp;$("statCompleted").textContent=`${done}/${modules.length}`;$("statProgress").textContent=`${Math.round(done/modules.length*100)}%`}
function renderFilters(){let cats=["All",...new Set(modules.map(m=>m.cat))];$("filterRow").innerHTML=cats.map(c=>`<button class="filter-chip-new ${filter===c?"active":""}" data-filter="${c}" type="button">${c}</button>`).join("")}
function renderModules(){let q=($("moduleSearch").value||"").toLowerCase();let shown=modules.filter(m=>(filter==="All"||m.cat===filter)&&`${m.title} ${m.desc} ${m.cat}`.toLowerCase().includes(q));$("moduleGrid").innerHTML=shown.map(m=>`<article class="module-card-new ${selected===m.id?"selected":""}" data-module="${m.id}"><div class="module-card-top"><div class="module-emoji">${m.emoji}</div><span class="module-tag-new ${state.done[m.id]?"done":"todo"}">${state.done[m.id]?"Done":getPercent(m.id)+"%"}</span></div><div class="module-name-new">${m.title}</div><p class="module-desc-new">${m.desc}</p><div class="module-tags-new"><span class="module-tag-new">${m.cat}</span><span class="module-tag-new">+${m.xp} XP</span></div><div class="module-progress"><span style="width:${getPercent(m.id)}%"></span></div></article>`).join("")}
function renderDetail(){let m=getModule(selected);state.last=selected;saveState();$("moduleDetail").innerHTML=`<div class="selected-title-row"><div class="module-emoji">${m.emoji}</div><div><h3>${m.title}</h3><p>${m.cat} • +${m.xp} XP</p></div></div><div class="module-progress"><span style="width:${getPercent(m.id)}%"></span></div><div class="training-tabs-new"><button class="training-tab-new ${tab==="lesson"?"active":""}" data-tab="lesson">📘 Lesson</button><button class="training-tab-new ${tab==="checklist"?"active":""}" data-tab="checklist">✅ Checklist</button><button class="training-tab-new ${tab==="quiz"?"active":""}" data-tab="quiz">🧠 Quiz</button><button class="training-tab-new ${tab==="tips"?"active":""}" data-tab="tips">💡 Tips</button></div><div class="tab-content-new" id="detailContent"></div>`;renderTab()}
function renderTab(){let m=getModule(selected),c=getChecks(selected),e=$("detailContent");if(tab==="lesson")e.innerHTML=`<ul class="lesson-list-new">${m.lesson.map(x=>`<li>${x}</li>`).join("")}</ul>`;if(tab==="checklist")e.innerHTML=`<div class="checklist-new">${m.checks.map((x,i)=>`<label class="check-item-new"><input type="checkbox" data-check="${i}" ${c[i]?"checked":""}><span>${x}</span></label>`).join("")}</div>`;if(tab==="quiz")e.innerHTML=`<div class="quiz-box-new"><div class="quiz-question-new">${m.q}</div>${m.opts.map((o,i)=>`<button class="quiz-option-new" data-answer="${i}" ${state.done[m.id]?"disabled":""}>${o}</button>`).join("")}${state.done[m.id]?`<span class="module-tag-new done">Completed</span>`:""}</div>`;if(tab==="tips")e.innerHTML=`<ul class="tips-list-new">${m.tips.map(x=>`<li>${x}</li>`).join("")}</ul>`}
function complete(m){if(state.done[m.id])return;state.done[m.id]=true;state.xp+=m.xp;saveState();toast(`Completed ${m.title}! +${m.xp} XP`)}
function render(){renderStats();renderFilters();renderModules();renderDetail()}
$("moduleSearch").addEventListener("input",renderModules);
$("filterRow").addEventListener("click",e=>{let b=e.target.closest("[data-filter]");if(!b)return;filter=b.dataset.filter;render()});
$("moduleGrid").addEventListener("click",e=>{let c=e.target.closest("[data-module]");if(!c)return;selected=c.dataset.module;tab="lesson";render()});
$("moduleDetail").addEventListener("click",e=>{let t=e.target.closest("[data-tab]");if(t){tab=t.dataset.tab;renderDetail()}let ch=e.target.closest("[data-check]");if(ch){getChecks(selected)[+ch.dataset.check]=ch.checked;saveState();render()}let a=e.target.closest("[data-answer]");if(a){let m=getModule(selected),i=+a.dataset.answer,ops=[...document.querySelectorAll(".quiz-option-new")];ops.forEach(o=>o.disabled=true);if(i===m.a){a.classList.add("correct");complete(m)}else{a.classList.add("wrong");ops[m.a]?.classList.add("correct");toast("Try again after reviewing the lesson.")}setTimeout(render,900)}});
$("continueBtn").addEventListener("click",()=>{selected=(modules.find(m=>!state.done[m.id])||modules[0]).id;tab="lesson";render();$("moduleDetail").scrollIntoView({behavior:"smooth",block:"center"})});
$("quickQuizBtn").addEventListener("click",()=>{tab="quiz";renderDetail();$("moduleDetail").scrollIntoView({behavior:"smooth",block:"center"})});
$("resetProgressBtn").addEventListener("click",()=>{state={xp:0,done:{},checks:{},last:selected};saveState();render();toast("Progress reset")});
render();
if(getUrlModule()) setTimeout(()=>$("moduleDetail")?.scrollIntoView({behavior:"smooth",block:"center"}),350);