// Shared fixtures for the end-to-end specs.
//
// Every test gets:
//   - freshly wiped + seeded Auth/Firestore emulators (auto fixture), so specs
//     are independent and can run in any order;
//   - browser contexts whose /firebase-init.js is swapped for a copy of the
//     real one that points at the emulators (connectAuthEmulator +
//     connectFirestoreEmulator, projectId demo-cccs). No production code
//     changes are needed;
//   - a hard block on every production Firebase / waste endpoint. If a page
//     ever tries to reach them the test fails.
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { test as base, expect } from "@playwright/test";
import {
  SEED,
  adminFor,
  daysFromToday,
  resetAndSeed,
  weekDates,
} from "../../scripts/e2e-seed.mjs";
import { E2E_PROJECT_ID, FIRESTORE_HOST, AUTH_HOST } from "../../scripts/e2e-guard.mjs";

export { expect, SEED, weekDates, daysFromToday };

const SDK = "https://www.gstatic.com/firebasejs/10.12.0";

// Build the emulator variant of firebase-init.js from the real file so the
// app config stays identical apart from the project ID.
export function emulatorFirebaseInit() {
  const source = readFileSync(resolve("firebase-init.js"), "utf8");
  const match = source.match(/const\s+firebaseConfig\s*=\s*(\{[\s\S]*?\});/);
  if (!match) throw new Error("Could not find firebaseConfig in firebase-init.js");
  const config = Function('"use strict";return (' + match[1] + ");")();
  config.projectId = E2E_PROJECT_ID;
  config.authDomain = E2E_PROJECT_ID + ".firebaseapp.com";
  delete config.measurementId;
  const sdk = source.match(/https:\/\/www\.gstatic\.com\/firebasejs\/[\d.]+/)?.[0] || SDK;
  const [fsHost, fsPort] = FIRESTORE_HOST.split(":");
  return `// e2e: emulator build of firebase-init.js (generated by tests/e2e/fixtures.mjs)
import { initializeApp } from "${sdk}/firebase-app.js";
import { getAuth, connectAuthEmulator } from "${sdk}/firebase-auth.js";
import { getFirestore, connectFirestoreEmulator } from "${sdk}/firebase-firestore.js";
const firebaseConfig = ${JSON.stringify(config, null, 2)};
const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
connectAuthEmulator(auth, "http://${AUTH_HOST}", { disableWarnings: true });
const db = getFirestore(app);
connectFirestoreEmulator(db, "${fsHost}", ${Number(fsPort)});
const analytics = null;
window.__e2eFirebase = { app, auth, db };
export { app, auth, db, analytics };
`;
}

// Matched against the HOSTNAME only: the Auth emulator legitimately serves
// paths such as http://127.0.0.1:9099/identitytoolkit.googleapis.com/…
const PRODUCTION_HOSTS =
  /(^|\.)(firestore\.googleapis\.com|identitytoolkit\.googleapis\.com|securetoken\.googleapis\.com|firebaseinstallations\.googleapis\.com|firebase\.googleapis\.com|firebaseio\.com|haylewaster\.vercel\.app|api\.openai\.com)$/;

// The Firebase web SDK and Google Fonts are fetched once per test worker and
// then served from memory, so each new browser context does not download
// them again (a big speed-up, especially for WebKit).
const CDN = /^https:\/\/(www\.gstatic\.com\/firebasejs\/|fonts\.googleapis\.com\/|fonts\.gstatic\.com\/)/;
const cdnCache = new Map();

async function serveCdn(route) {
  const url = route.request().url();
  if (route.request().method() !== "GET") return route.continue();
  let hit = cdnCache.get(url);
  if (!hit) {
    try {
      const response = await route.fetch();
      if (!response.ok()) return route.fulfill({ response });
      // body() is already decoded: drop encoding/length headers.
      const headers = Object.fromEntries(
        Object.entries(response.headers()).filter(([k]) => !/^(content-encoding|content-length|transfer-encoding)$/i.test(k)),
      );
      hit = { status: response.status(), headers, body: await response.body() };
      cdnCache.set(url, hit);
    } catch {
      return route.continue().catch(() => {});
    }
  }
  return route.fulfill({ status: hit.status, headers: hit.headers, body: hit.body });
}

// Note: the emulator speaks HTTP/1.1 (six connections per browser context)
// and Playwright's WebKit on Windows keeps connections of pages it has left.
// Specs that visit many pages open a fresh context per page (layout.spec).
export async function prepareContext(context, blocked) {
  const init = emulatorFirebaseInit();
  await context.route(/\/firebase-init\.js(\?.*)?$/, (route) =>
    route.fulfill({ status: 200, contentType: "text/javascript; charset=utf-8", body: init }),
  );
  await context.route(CDN, serveCdn);
  await context.route((url) => PRODUCTION_HOSTS.test(url.hostname), (route) => {
    blocked.push(route.request().method() + " " + route.request().url());
    return route.abort("blockedbyclient");
  });
}

export const test = base.extend({
  // Wipe + seed before every test (runs even if the test does not use it).
  seeded: [
    async ({}, use) => {
      await resetAndSeed();
      // Fresh fake upstreams too (ignore if a spec runs without them).
      await Promise.all(
        ["http://127.0.0.1:4011/__e2e/reset", "http://127.0.0.1:4010/__e2e/reset"].map((url) =>
          fetch(url, { method: "POST", body: "{}" }).catch(() => null),
        ),
      );
      await use(SEED);
    },
    { auto: true },
  ],
  blockedRequests: [
    async ({}, use) => {
      const blocked = [];
      await use(blocked);
      expect(blocked, "The app tried to reach a production endpoint").toEqual([]);
    },
    { auto: true },
  ],
  context: async ({ context, blockedRequests }, use) => {
    await prepareContext(context, blockedRequests);
    await use(context);
  },
  admin: async ({}, use) => {
    await use(adminFor("e2e-tests"));
  },
  // Opens a second, fully isolated browser session (e.g. crew + manager side
  // by side) with the same emulator routing and device settings. Pass
  // { storageState } to reuse a signed-in session in a fresh browser context.
  newSession: async ({ browser, blockedRequests }, use, testInfo) => {
    const contexts = [];
    await use(async (options = {}) => {
      const { baseURL, viewport, userAgent, deviceScaleFactor, isMobile, hasTouch, locale, timezoneId, reducedMotion } =
        testInfo.project.use;
      const context = await browser.newContext({
        baseURL,
        viewport,
        userAgent,
        deviceScaleFactor,
        isMobile,
        hasTouch,
        locale,
        timezoneId,
        reducedMotion,
        ...options,
      });
      contexts.push(context);
      await prepareContext(context, blockedRequests);
      return context.newPage();
    });
    await Promise.all(contexts.map((c) => c.close()));
  },
});

// ------------------------------------------------------------ UI helpers
export async function signIn(page, who) {
  const user = typeof who === "string" ? SEED.users[who] : who;
  await page.goto("/");
  await page.getByLabel(/email/i).fill(user.email);
  await page.getByLabel(/^password/i).fill(user.password || SEED.password);
  const roleData = page
    .waitForResponse((r) => new URL(r.url()).pathname === "/api/portal-data", { timeout: 30000 })
    .catch(() => null);
  await page.getByRole("button", { name: /^sign in/i }).click();
  await page.waitForURL(/\/main(\.html)?(\?|$)/, { timeout: 20000 });
  await roleData;
  await waitForHub(page);
  return user;
}

// The shell renders first; portal-enhancements.js then loads role data from
// /api/portal-data and applies the role UI (it injects the verification link
// into the navigation). Wait for that so tests act on the finished page.
export async function waitForHub(page) {
  await expect(page.locator("#content")).not.toBeEmpty({ timeout: 20000 });
  await expect(page.locator('a[href^="/verification.html"]').first()).toBeAttached({ timeout: 20000 });
}

// Sign-out triggers two navigations (the click handler and the auth listener),
// so poll the URL instead of waiting for a single navigation event.
export async function expectSignedOut(page) {
  await expect(page).toHaveURL(/127\.0\.0\.1:\d+\/(index\.html)?(\?.*)?$/, { timeout: 20000 });
  await expect(page.getByRole("button", { name: /^sign in/i })).toBeVisible();
}

// The primary navigation is the sidebar on desktop and the bottom bar on
// phones/tablets; return whichever is visible.
export function mainNav(page) {
  return page
    .getByRole("navigation", { name: /Main navigation|Mobile navigation/ })
    .filter({ visible: true })
    .first();
}

export async function openProfile(page) {
  await page.getByRole("button", { name: /my profile/i }).click();
  const dialog = page.getByRole("dialog");
  await expect(dialog).toBeVisible();
  return dialog;
}

// Sends one McAssist message through the real UI and returns the JSON the
// real /api/ai-chat endpoint answered with.
export async function askMcAssist(page, message) {
  const input = page.getByRole("textbox", { name: "Message McAssist" });
  await input.fill(message);
  const responsePromise = page.waitForResponse(
    (r) => /\/api\/(ai-chat|mcassist)$/.test(new URL(r.url()).pathname) && r.request().method() === "POST",
    { timeout: 45000 },
  );
  await page.getByRole("button", { name: "Send message", exact: true }).click();
  const response = await responsePromise;
  const body = await response.json().catch(() => ({}));
  return { status: response.status(), body };
}

// Clicks a pending-plan button (e.g. its confirmLabel) and returns the JSON of
// the confirm request.
export async function resolvePending(page, label) {
  const responsePromise = page.waitForResponse(
    (r) => /\/api\/(ai-chat|mcassist)$/.test(new URL(r.url()).pathname) && r.request().method() === "POST",
    { timeout: 45000 },
  );
  await page.getByRole("button", { name: label, exact: true }).last().click();
  const response = await responsePromise;
  const request = response.request().postDataJSON?.() || {};
  return { status: response.status(), body: await response.json().catch(() => ({})), request };
}

// Clicks a control inside a modal sheet by its on-screen position (real hit
// testing, like a finger). Playwright's locator.click() in WebKit iPhone
// emulation first "scrolls into view" a sticky footer inside the scroll-locked
// sheet, which moves the visual viewport so the click lands outside the page.
export async function pressVisible(page, locator) {
  await expect(locator).toBeVisible();
  await expect(locator).toBeEnabled();
  const box = await locator.boundingBox();
  const view = page.viewportSize();
  const inView = box && view && box.y >= 0 && box.x >= 0 && box.y + box.height <= view.height && box.x + box.width <= view.width;
  if (!inView) return locator.click();
  await page.mouse.click(box.x + box.width / 2, box.y + box.height / 2);
}

// Calls an API route from inside the page with the signed-in user's real
// Firebase ID token (waits for Auth to restore the session first).
export async function pageApi(page, path, body) {
  await page.waitForFunction(() => Boolean(window.__e2eFirebase?.auth), null, { timeout: 20000 });
  return page.evaluate(
    async ({ path, body }) => {
      const { auth } = window.__e2eFirebase;
      await auth.authStateReady();
      const token = await auth.currentUser.getIdToken();
      const r = await fetch(path, {
        method: body ? "POST" : "GET",
        headers: { "Content-Type": "application/json", Authorization: "Bearer " + token },
        body: body ? JSON.stringify(body) : undefined,
      });
      return { status: r.status, body: await r.json().catch(() => ({})) };
    },
    { path, body },
  );
}

// Draws a short squiggle on a signature canvas using pointer events.
export async function drawSignature(page, canvas) {
  await canvas.scrollIntoViewIfNeeded();
  const box = await canvas.boundingBox();
  if (!box) throw new Error("Signature canvas is not visible");
  const x = box.x + 20;
  const y = box.y + box.height / 2;
  await page.mouse.move(x, y);
  await page.mouse.down();
  for (let i = 1; i <= 12; i++) await page.mouse.move(x + i * 12, y + (i % 2 ? -18 : 18), { steps: 2 });
  await page.mouse.up();
}

// ---------------------------------------------------------- data helpers
export async function shiftsFor(admin, uid, storeId = SEED.store.id) {
  const snap = await admin.db.collection(`stores/${storeId}/Shifts`).where("userId", "==", uid).get();
  return snap.docs.map((d) => ({ id: d.id, ...d.data() }));
}

export async function userDoc(admin, uid) {
  const snap = await admin.db.doc("users/" + uid).get();
  return snap.exists ? snap.data() : null;
}

export async function authUserExists(admin, uid) {
  try {
    await admin.auth.getUser(uid);
    return true;
  } catch (error) {
    if (error.code === "auth/user-not-found") return false;
    throw error;
  }
}

export const dayLabel = (date, options = { weekday: "short", day: "numeric", month: "short" }) =>
  new Date(`${date}T12:00`).toLocaleDateString("en-GB", options);
